blank_issues_enabled: false
contact_links:
  - name: ğŸ“– ãƒ—ãƒ­ã‚¸ã‚§ã‚¯ãƒˆãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ (APIè¨­ç½®)
    url: https://github.com/AgAmemnno/copilot-web-demo
    about: ã¾ãšã¯ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆã‚’ã”ç¢ºèªãã ã•ã„ã€‚